<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sachin-Sharma" ignored="1" name="sanity test" tests="3" failures="1" timestamp="06 Oct 2022 03:59:07 GMT" time="39.991" errors="0">
  <testcase name="verifyLoginPageTitleTest" time="0.131" classname="com.qa.trcrm.tests.LoginPageTest"/>
  <testcase name="verifySignUpLinkTest" time="0.229" classname="com.qa.trcrm.tests.LoginPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.qa.trcrm.utils.ElementUtil.doIsDisplayed(ElementUtil.java:41)
at com.qa.trcrm.pages.LoginPage.verifySignUpLink(LoginPage.java:35)
at com.qa.trcrm.tests.LoginPageTest.verifySignUpLinkTest(LoginPageTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifySignUpLinkTest -->
  <testcase name="doLoginTest" time="13.188" classname="com.qa.trcrm.tests.LoginPageTest"/>
  <testcase name="login_InvalidTestCases" time="0.0" classname="com.qa.trcrm.tests.LoginPageTest">
    <ignored/>
  </testcase> <!-- login_InvalidTestCases -->
</testsuite> <!-- sanity test -->
